<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerExrlqdk\appProdProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerExrlqdk/appProdProjectContainer.php') {
    touch(__DIR__.'/ContainerExrlqdk.legacy');

    return;
}

if (!\class_exists(appProdProjectContainer::class, false)) {
    \class_alias(\ContainerExrlqdk\appProdProjectContainer::class, appProdProjectContainer::class, false);
}

return new \ContainerExrlqdk\appProdProjectContainer([
    'container.build_hash' => 'Exrlqdk',
    'container.build_id' => 'fd2ddc35',
    'container.build_time' => 1599044635,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerExrlqdk');
